#
# https://gitlab.com/gitlab-org/gitlab-runner/blob/master/.gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/
# https://gitlab.com/ci/lint
#
before_script:
- source /data/pythons/sphinx/bin/activate



#after_script:
#  - cp -vf docs/build/* /data/odc/


stages:
- build



sit_build_job:
  stage: build
  script:
  - ./build.doc.sh
  only:
  - master

